In [1]:
import numpy as np

In [3]:
# ejercicio 1 a partir de una lista crear un arreglo 
l1 = [1,2,3,4,5,]
arreglo = np.array(l1)
print(arreglo)

[1 2 3 4 5]


In [6]:
# ejercicio 2 crear un arreglo con 9 elementos
# y otro con 100 elementos equidistanciados del 0 al 9 con linspace

arreglo1 = np.array(9)
arreglo2 = np.linspace(0,9,100)  #

print(arreglo1)
print(arreglo2)

9
[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.
 1.09090909 1.18181818 1.27272727 1.36363636 1.45454545 1.54545455
 1.63636364 1.72727273 1.81818182 1.90909091 2.         2.09090909
 2.18181818 2.27272727 2.36363636 2.45454545 2.54545455 2.63636364
 2.72727273 2.81818182 2.90909091 3.         3.09090909 3.18181818
 3.27272727 3.36363636 3.45454545 3.54545455 3.63636364 3.72727273
 3.81818182 3.90909091 4.         4.09090909 4.18181818 4.27272727
 4.36363636 4.45454545 4.54545455 4.63636364 4.72727273 4.81818182
 4.90909091 5.         5.09090909 5.18181818 5.27272727 5.36363636
 5.45454545 5.54545455 5.63636364 5.72727273 5.81818182 5.90909091
 6.         6.09090909 6.18181818 6.27272727 6.36363636 6.45454545
 6.54545455 6.63636364 6.72727273 6.81818182 6.90909091 7.
 7.09090909 7.18181818 7.27272727 7.36363636 7.45454545 7.54545455
 7.63636364 7.72727273 7.81818182 7.90909091 8.         8.09090909
 8.181818

In [10]:
# ejercicio 3 crear un arreglo con elementos elementos entre 10 y 100, y mostrar solo los elementos divisibles entre 3 

a = np.arange(10,100)
mascara = ((a%3) == 0)

print(a[mascara])

[12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81
 84 87 90 93 96 99]


In [17]:
#ejercicio 4 crear un arreglo de ceros de shape (5,10)
#reenplazar la cuarta y segunda fila con unos 
# reemplazar la tercera y octava fila con 2 

arreglo5 = np.zeros((5,10))
arreglo5[1,:] = 1 # lo que esta entre [] el primero representa las filas y el segundo despues de ',' son las columnas
arreglo5[3,:] = 1
arreglo5[:,[2,7]] = 2 #para sustituir dos columnas de forma mas eficiente usar un par mas de []
print(arreglo5)

[[0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]
 [1. 1. 2. 1. 1. 1. 1. 2. 1. 1.]
 [0. 0. 2. 0. 0. 0. 0. 2. 0. 0.]]
